import json
import openai
import tiktoken
import copy
import numpy as np
import pandas as pd
import torch
from alphagen.data.expression import *
from alphagen.utils.pytorch_utils import normalize_by_day
from alphagen.utils.correlation import batch_pearsonr, batch_spearmanr
from alphagen_qlib.calculator import *
from alphagen_qlib.stock_data import *

from logger import *

logger = Logger().get_logger()

openai.api_key = "your_openai_api_key"

# =============================================================================
# Some utility functions

# display code formatting
def format_for_display(code):
    code = code.replace("```python", "").replace("```", "").replace("<end>", "")
    return code


# execute code generated by LLMs
def run_llm_code(code, df):
    try:
        loc = {}
        df = copy.deepcopy(df)
        access_scope = {"df": df, "pd": pd, "np": np}
        exec(code, access_scope, loc)
        df = copy.deepcopy(df)

    except Exception as e:
        logger.error(f"\nCode could not be executed, {e}",
                     extra={'module_name': "run_llm_code"})
        raise e

    return df

# error detector: check whether the code is executable and whether it uses future information,
# where future information is detected by checking whether the output alpha changes when adding future data
def check_alpha_code_valid(code):
    day = 365
    stock_num = 5
    data = {
        'open': pd.DataFrame(np.random.rand(day, stock_num)),
        'high': pd.DataFrame(np.random.rand(day, stock_num)),
        'low': pd.DataFrame(np.random.rand(day, stock_num)),
        'close': pd.DataFrame(np.random.rand(day, stock_num)),
        'vwap': pd.DataFrame(np.random.rand(day, stock_num)),
        'volume': pd.DataFrame(np.random.rand(day, stock_num))
    }
    new_data = copy.deepcopy(data)
    for i in data.keys():
        tmp = pd.DataFrame(np.random.rand(5, stock_num))
        base_df = data[i]
        new_data[i] = pd.concat([base_df, tmp], axis=0)


    try:
        df = run_llm_code(code, data)['alpha']
        df_new = run_llm_code(code, new_data)['alpha']
        cut = df.iloc[:day]
        cut_new = df_new.iloc[:day]
        are_equal = cut.equals(cut_new)
        code_runnable = True
    except Exception as e:
        logger.error(f"\nError in code execution.\n{type(e)} {e}",
                     extra={'module_name': "check_alpha_code_valid"})
        code_runnable = False
        are_equal = False

    return code_runnable, are_equal


# =============================================================================
# Code Generation Process

# prompt for code generation
def get_prompt_for_code_generation(alpha_description, samples=None):
    return f""" Firstly, I will introduce basic information about the input data:
1. The input data, referred to as 'df', is a Python dictionary that contains six DataFrames obtained from baostock and provides historical data for a specific stock, named 'open', 'close', 'high', 'low', 'volume', 'vwap'
2. Each DataFrame's columns correspond to stock names, and the rows are indexed by a DateTimeIndex. 
3. Each of them represents a specific aspect of the stock's performance and financial metrics, enabling users to track its fluctuations over time.
4. This data will be loaded and used in the subsequent code you generate.

Features in `df`(true feature dtypes listed here): 
{samples}

The functions and operators used in the alphas are defined below: (All expressions are case insensitive.)
1. Same for the operators “+”, “-”, “*”, “/”, “>”, “<”, “==”, “||”, “x ? y : z”
2. Common functions and their explanations as follows, some of which include code example('yy' represents the alias of a certain feature):
    2.1 abs(x), log(x), sign(x) = standard definitions; 
    2.2 rank(x) = cross-sectional rank of stocks, it means all stocks are ranked at the same time point. Code example: df['yy'].rank(axis=1);
    2.3 delay(x, d) = value of x d days ago;
    2.4 correlation(x, y, d) = time-serial correlation of x and y for the past d days;
    2.5 covariance(x, y, d) = time-serial covariance of x and y for the past d days;
    2.6 scale(x, a) = rescaled x such that sum(abs(x)) = a (the default is a = 1). Code example: df['yy'].apply(lambda row: row * k / np.abs(row).sum(), axis=1);
    2.7 delta(x, d) = today’s value of x minus the value of x d days ago;
    2.8 signedpower(x, a) = x^a;
    2.9 decay_linear(x, d) = weighted moving average over the past d days with linearly decaying weights d, d – 1, ..., 1 (rescaled to sum up to 1);
    2.10 ts_O(x, d) = operator O applied across the time-series for the past d days; non-integer number of days d is converted to floor(d);
    2.11 ts_min(x, d) = time-series min over the past d day;
    2.12 ts_max(x, d) = time-series max over the past d days;
    2.13 ts_argmax(x, d) = which day ts_max(x, d) occurred on;
    2.14 ts_argmin(x, d) = which day ts_min(x, d) occurred on;
    2.15 ts_rank(x, d) = time-series rank in the past d days;
    2.16 sum(x, d) = time-series sum over the past d days;
    2.17 product(x, d) = time-series product over the past d days;
    2.18 stddev(x, d) = moving time-series standard deviation over the past d days.
    
Task:
    1. Given the `df` and the Alpha Description, you need to write a python code to implement the quantitative Alpha.
    2. This code should generate a new additional feature called `alpha` to `df` that serves as a key metric in evaluating the effectiveness and skill of investment strategies, helping investors identify opportunities for superior returns. Make sure all used features exist. Follow the above description of features closely and consider the datatypes and meanings of operators and functions used in Alpha. Make sure the generated code does not use future information.

There are some important notes that you should follow: 
    1. rank(x) is totally different from ts_rank(x,d). rank(x) is cross-sectional rank, while ts_rank(x, d) is time-series rank in the past d days. If you need to implement 'rank(x)', you should use 'x.rank(axis=1, pct=True)' or other codes to implement cross-sectional rank, you cannot use 'x.rank(pct=True)' to implement this function, because it's time-series rank.
    2. Please remember that the new feature you generate must be formatted as a DataFrame. Be sure to use pd.DataFrame(x) to align the format in a timely manner, and do not represent it as np.ndarray or any other format.
    3. You should remember that each codeblock ends with ```end and starts with "```python".

Code formatting for each codeblock:
```python
# (Alpha description)
# ... Finally you need to add a new feature named 'alpha' to `df`: df['alpha'] = ...
```end

Example:
Alpha Description:
(rank(Ts_ArgMax(SignedPower(((returns < 0) ? stddev(returns, 20) : close), 2.), 5)) -0.5)

Codeblock:
```python
# Calculate daily returns
df['returns'] = df['close'].pct_change()
# Calculate standard deviation of returns over a 20-day period
df['stddev_returns_20'] = df['returns'].rolling(window=20).std()
# Create a mask to identify negative returns
negative_returns_mask = df['returns'] < 0
# Compute the SignedPower factor, using either the standard deviation or the closing price, based on the sign of returns
# remember to change 'np.ndarray' to pd.dataframe
df['SignedPower'] = pd.DataFrame(np.where(negative_returns_mask, df['stddev_returns_20'], df['close']) ** 2)
# Rank the Ts_ArgMax (index of the maximum value) over the past 5 days
df['Ts_ArgMax'] = df['SignedPower'].rolling(window=5).apply(lambda x: np.argmax(x), raw=True)
# Rank the results and subtract 0.5
df['alpha'] = df['Ts_ArgMax'].rank(axis=1, pct=True) - 0.5
```end

Then, I will give you an alpha description, please complete the codeblock
Alpha Description:
{alpha_description}
Codeblock:
"""

# build prompt for code generation; df is a dictionary of DataFrames for sampling, which is used to show the data format
def build_prompt_from_df_for_code_generation(df, alpha_description):
    samples = ""
    features = ['open', 'close', 'high', 'low', 'volume', 'vwap']
    for feature in features:
        samples = samples + f"The samples for `df['{feature}']` is:\n"
        df_ = df[feature].iloc[:2, :5]
        samples += df_.to_string()
        samples += '\n'

    prompt = get_prompt_for_code_generation(
        alpha_description=alpha_description,
        samples=samples
    )

    return prompt

# get response from openai for code generation
def get_response_for_code(messages, model="gpt-3.5-turbo"):
    try_num = 0
    while try_num < 3:
        try:
            completion = openai.ChatCompletion.create(
                model=model,
                messages=messages,
                stop=["```end"],
                temperature=0.5,
                max_tokens=600,
            )
            response = completion["choices"][0]["message"]["content"]
            logger.warning(f"Get_response:\n {response}",
                           extra={'module_name': "get_response_for_code"})
            code = response
            code = code.replace("```python", "").replace("```end", "").replace("```", "").replace("<end>", "")
            return code, response
        except Exception as e:
            try_num += 1
            logger.error(f"\nAn error occurred in Openai: {str(e)}",
                         extra={'module_name': "get_response_for_code"})
    return "OpenAI API Error"

def generate_code(new_alpha, model, code_response_list, df_for_exec):
    e, code = None, None
    prompt_for_code_generation = build_prompt_from_df_for_code_generation(df_for_exec, new_alpha)
    messages_for_code_generation = [
        {
            "role": "system",
            "content": "You are an expert in quantitative finance trading, proficient and knowledgeable in "
                       "quantitative alpha factors. You task is to generate code base on the alpha. You answer only by generating code. Please answer as "
                       "concisely as possible.",
        },
        {
            "role": "user",
            "content": prompt_for_code_generation,
        },
    ]
    try_num = 0
    while try_num < 3:
        try_num += 1
        try:
            code, code_response = get_response_for_code(messages_for_code_generation, model=model)
            code_response_list.append(code_response)
        except Exception as es:
            logger.error(f"\nError in LLM Generating Codeblock for the new alpha. \n{es}",
                         extra={'module_name': "generate_alpha_code_and_fitness"})
            continue

        assert code is not None, "Error in Code generation."

        # 0. Check Code is executable and doesn't use future information.
        code_runnable, are_equal = check_alpha_code_valid(code)
        logger.warning(f"\nThe equal test results : {are_equal}\n",
                       extra={'module_name': "generate_code"})
        # 1. Code is Unexexcutable
        if code_runnable is False:
            messages_for_code_generation += [
                {"role": "assistant", "content": code},
                {
                    "role": "user",
                    "content": f"""Code execution failed with error: {type(e)} {e}.\n Code: ```python{code}```\n.Generate new code (fixing error?)(You answer only by generating code):
                                                           ```python
                                                           """,
                },
            ]
            continue

        # 2. Code is excutable But Use future information
        if are_equal is False:
            logger.error(f"\nRegenerate! The equal test results don't equal\n",
                         extra={'module_name': "generate_code"})
            messages_for_code_generation += [
                {"role": "assistant", "content": code},
                {
                    "role": "user",
                    "content": f"""The feature should only use information from the current and past data, and should not use any future data. For example, using df['open'].sum() would use all time periods' df['open'], but I want the generated code to avoid using future data points. Please ensure that the code adheres to this requirement.
                    The code you generate: \n Code: ```python{code}```\n Please generate new code, please follow my requirement to fix it:
                                                           ```python
                                                           """,
                },
            ]
            continue

        # 3. Code is excutable and doesn't use future information
        if code_runnable and are_equal:
            return None, code
    return e, None

# =============================================================================
# Code Evaluation Process

# evaluate the alphas by calculating IC and IR, which is implemented by ALPHAGEN.
def calculate_fitness(df_alphas, target_value, start_date, end_date):
    try:
        df_alphas = df_alphas[(df_alphas.index >= start_date) & (df_alphas.index <= end_date)]
        df_alphas_values = df_alphas.values
        df_alphas_values_tensor = torch.tensor(df_alphas_values, dtype=torch.float, device='cuda:0')

        df_alphas_values_tensor = normalize_by_day(df_alphas_values_tensor)

        normal_ic = batch_pearsonr(df_alphas_values_tensor, target_value).mean().item()
        normal_ic_std = batch_pearsonr(df_alphas_values_tensor, target_value).std().item()
        normal_ir = normal_ic / normal_ic_std if normal_ic_std != 0 else 0

        torch.cuda.empty_cache()

        rank_ic = batch_spearmanr(df_alphas_values_tensor, target_value).mean().item()
        rank_ic_std = batch_spearmanr(df_alphas_values_tensor, target_value).std().item()
        rank_ir = rank_ic / rank_ic_std if rank_ic_std != 0 else 0

        fitness_value = normal_ic

        logger.debug(
            f"Normal IC:  {normal_ic}, Rank IC:  {rank_ic}",
            extra={'module_name': "calculate_fitness"})

        return normal_ic, normal_ir, rank_ic, rank_ir, fitness_value
    except Exception as e:
        return None, None, None, None, None


# execute and evaluate the code block for an alpha
def execute_and_evaluate_code_block_for_alpha(code, df_for_exec, target_value, start_date, end_date):
    try:
        df_before = copy.deepcopy(df_for_exec)
        df_after = run_llm_code(
            "" + "\n" + code,
            df_before
        )
        df_alphas = df_after['alpha']

    except Exception as e:
        logger.error(
            f"\nError in code execution.\n{type(e)} {e}\n ```python\n{format_for_display(code)}\n```\n",
            extra={'module_name': "execute_and_evaluate_code_block_for_alpha"})

        return e, None, None, None, None, None, None
    print(df_alphas)
    normal_ic, normal_ir, rank_ic, rank_ir, fitness_value = calculate_fitness(df_alphas, target_value,
                                                                              start_date, end_date)
    logger.warning(
        f'\nnormal_ic: {normal_ic}\nnormal_ir: {normal_ir}\nrank_ic: {rank_ic}\nrank_ir: {rank_ir}\nfitness_value: {fitness_value}\n',
        extra={'module_name': "execute_and_evaluate_code_block_for_alpha"}
    )
    return None, normal_ic, normal_ir, rank_ic, rank_ir, fitness_value, df_alphas


if __name__ == "__main__":
    instruments = "csi300"
    holding_days = 20
    start_date = "2009-01-01"
    end_date = "2018-12-31"

    # load market data from Qlib, which is implemented by ALPHAGEN and Qlib.
    close = Feature(FeatureType.CLOSE)
    target = Ref(close, - 1 - holding_days) / Ref(close, -1) - 1
    data = StockData(instrument=instruments,
                           start_time=start_time,
                           end_time=end_time)
    calculator = QLibStockDataCalculator(data, target)

    # Calculator calculates the formula `target` defined above, which means Future Returns.
    target_value = calculator.target_value

    df, dates, stock_ids = data.get_df_dates_stocks()
    # Please NOTE THAT QlibStockData does not have `get_df_dates_stocks` method, which is implemented by ours, as Qlib does not provide such an interface:
    # def get_df_dates_stocks(self):
    #     features = ['$' + f.name.lower() for f in self._features]
    #     df = self._load_exprs(features)
    #     df = df.stack(dropna=False).unstack(level=1)
    #     dates = df.index.levels[0]  # type: ignore
    #     stock_ids = df.columns
    #     return df, dates, stock_ids

    ############ Prepare df_for_exec ############
    features = ['open', 'close', 'high', 'low', 'volume', 'vwap']
    df_for_exec = {}
    for feature in features:
        df_for_exec[feature] = pd.concat(
            [df.loc[(i, f'${feature}')] for i in dates], axis=1
        ).transpose()
        df_for_exec[feature].columns = stock_ids
        df_for_exec[feature].index = dates
    #############################################
    # Why we need `df_for_exec`?
    # Because the original `df` obtained from Qlib is a MultiIndex DataFrame, which is not convenient for code generation and execution.
    # We need to convert it into a dictionary of DataFrames for each feature, where each DataFrame has stocks as columns and dates as index.
    #############################################


    alpha = "your_alpha_description_here"
    model = "your_model_name_here"
    code_response_list = []
    e, code = generate_code(alpha, model, code_response_list, df_for_exec)
    if e is None:
        e, normal_ic, normal_ir, rank_ic, rank_ir, fitness_value, df_alphas_after_code_execution = execute_and_evaluate_code_block_for_alpha(
            code, df_for_exec, target_value,
            start_date, end_date
        )
        if e is None:
            print(f"Code executed successfully. Normal IC: {normal_ic}, Rank IC: {rank_ic}")
        else:
            print(f"Error in executing code: {e}")
    else:
        print(f"Error in generating code: {e}")

