import copy

import numpy as np
import pandas as pd

from logger import *

logger = Logger().get_logger()


def format_for_display(code):
    code = code.replace("```python", "").replace("```", "").replace("<end>", "")
    return code


# execute code generated by LLMs
def run_llm_code(code: str, df: pd.DataFrame) -> pd.DataFrame:
    try:
        loc = {}
        df = copy.deepcopy(df)
        access_scope = {"df": df, "pd": pd, "np": np}
        exec(code, access_scope, loc)
        df = copy.deepcopy(df)

    except Exception as e:
        logger.error(f"\nCode could not be executed, {e}",
                     extra={'module_name': "run_llm_code"})
        raise e

    return df


def check_alpha_code_valid(code):
    day = 365
    stock_num = 5
    data = {
        'open': pd.DataFrame(np.random.rand(day, stock_num)),
        'high': pd.DataFrame(np.random.rand(day, stock_num)),
        'low': pd.DataFrame(np.random.rand(day, stock_num)),
        'close': pd.DataFrame(np.random.rand(day, stock_num)),
        'vwap': pd.DataFrame(np.random.rand(day, stock_num)),
        'volume': pd.DataFrame(np.random.rand(day, stock_num))
    }
    new_data = copy.deepcopy(data)
    for i in data.keys():
        tmp = pd.DataFrame(np.random.rand(5, stock_num))
        base_df = data[i]
        new_data[i] = pd.concat([base_df, tmp], axis=0)


    try:
        df = run_llm_code(code, data)['alpha']
        df_new = run_llm_code(code, new_data)['alpha']
        cut = df.iloc[:day]
        cut_new = df_new.iloc[:day]
        are_equal = cut.equals(cut_new)
        code_runnable = True
    except Exception as e:
        logger.error(f"\nError in code execution.\n{type(e)} {e}",
                     extra={'module_name': "check_alpha_code_valid"})
        code_runnable = False
        are_equal = False

    return code_runnable, are_equal

